apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app.name }}
  minReplicas: {{ .Values.app.hpa.minReplicas }}
  maxReplicas: {{ .Values.app.hpa.maxReplicas }}
  metrics:
    - type: Pods
      pods:
        metric:
          name: {{ .Values.app.hpa.metricName }}
        target:
          type: AverageValue
          averageValue: {{ .Values.app.hpa.metricAverageValue }}