replicaCount: 1

image:
  pullPolicy: IfNotPresent
  registry: ghcr.io
  repository: atilsensalduz
  version: 36ce47d

app:
  name: exporter
  replicas: 1
  ports:
    - name: http
      value: 2112
  envs:
    - name: MAIN_APP_URL
      value: http://main.main
  annotations: {
    prometheus.io/path: "/metrics",
    prometheus.io/port: '2112',
    prometheus.io/scrape: 'true'
  }
