replicaCount: 1

image:
  pullPolicy: IfNotPresent
  registry: ghcr.io
  repository: atilsensalduz
  version: 7069726

app:
  name: exporter
  replicas: 1
  ports:
    - name: http
      value: 2112
  envs:
    - name: MAIN_APP_URL
      value: http://main.main:8080
  annotations: {
    prometheus.io/path: "/metrics",
    prometheus.io/port: '2112',
    prometheus.io/scrape: 'true'
  }

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
