replicaCount: 1

image:
  pullPolicy: IfNotPresent
  registry: ghcr.io
  repository: atilsensanlduz/main
  version: b230015

app:
  name: main
  replicas: 1
  ports:
    - name: http
      value: 8080

spec:
  destination:
    server: "https://kubernetes.default.svc"
  apps:
    repoURL: https://github.com/atilsensalduz/mf-sre
    main: 
      path: charts/main

