replicaCount: 1

image:
  pullPolicy: IfNotPresent
  registry: ghcr.io
  repository: atilsensanlduz/main
  version: 4991c75

app:
  name: main
  replicas: 1
  ports:
    - name: http
      value: 8080
