replicaCount: 1

image:
  pullPolicy: IfNotPresent
  registry: ghcr.io
  repository: atilsensalduz
  version: 2cf89c5

app:
  name: main
  replicas: 1
  ports:
    - name: http
      value: 8080
  hpa:
    minReplicas: 1
    maxReplicas: 15
    metricName: http_requests_total_sum
    metricAverageValue: 100
