image:
  pullPolicy: IfNotPresent
  registry: ghcr.io
  repository: atilsensalduz
  version: 4a01a71

app:
  name: main
  replicas: 1
  ports:
    - name: http
      value: 8080
  hpa:
    minReplicas: 1
    maxReplicas: 15
    metricName: http_requests_per_second
    metricAverageValue: 10
  
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

    