repoURL: https://prometheus-community.github.io/helm-charts
targetRevision: HEAD
prometheus-adapter:
  prometheus:
    url: http://prometheus-server
    port: 80
    path: ""
  rules:
    custom:
      - seriesQuery: 'rate(http_requests_total[1m])'
        resources:
          template: <<.Resource>>
        name:
          matches: ""
          as: "http_requests_total_per_min"
        metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)
