repoURL: https://prometheus-community.github.io/helm-charts
targetRevision: HEAD
prometheus-adapter:
  prometheus:
    url: http://prometheus-server
    port: 80
    path: ""
  rules:
    custom:
    - seriesQuery: 'http_requests_total{namespace!="",pod!=""}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod: 
            resource: pod
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: 'rate(<<.Series>>{<<.LabelMatchers>>}[1m]) by (<<.GroupBy>>)'
