repoURL: https://prometheus-community.github.io/helm-charts
targetRevision: HEAD
prometheus-adapter:
  prometheus:
    url: http://prometheus-server
    port: 80
    path: ""
  rules:
    custom:
      - seriesQuery: '{__name__=~"^http_requests_total$"}'
        resources:
          template: <<.Resource>>
        name:
          matches: ""
          as: "my_custom_metric"
        metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)
