repoURL: https://prometheus-community.github.io/helm-charts
targetRevision: HEAD
prometheus-adapter:
  prometheus:
    url: http://prometheus-server
    port: 80
    path: ""
  rules:
    custom:
    - seriesQuery: '{__name__=~"^http_requests_total$"}'
      resources:
        template: <<.Resource>>
      name:
        matches: "http_requests_total"
        as: http_requests_total_per_min"
      metricsQuery: 'rate(<<.Series>>[1m])'
