repoURL: https://prometheus-community.github.io/helm-charts
targetRevision: HEAD
prometheus-adapter:
  prometheus:
    url: http://prometheus-server
    port: 80
    path: ""
  rules:
    custom:
    - seriesQuery: 'http_requests_total{kubernetes_namespace!="",kubernetes_pod_name!=""}'
      resources:
        overrides:
          kubernetes_namespace: {resource: "namespace"}
          kubernetes_pod_name: {resource: "pod"}
      name:
        matches: "^(.*)_total"
        as: "${1}_custom"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)'
