apiVersion: v2
name: infra-component
description: App of Apps for Infra Components
type: application
version: 0.5.0
appVersion: 1.0.0

dependencies:
  - name: kube-prometheus-stack
    version: 45.15.0
    repository: https://prometheus-community.github.io/helm-charts
