apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: "argocd"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.kube-prometheus-stack.repoUrl }}
    targetRevision: {{ .Values.kube-prometheus-stack.targetRevision }}
    helm:
      skipCrds: true
      values: |
        kube-prometheus-stack:
        {{- toYaml .Values.kube-prometheus-stack.kubePrometheusStack | nindent 10 }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m