apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: "argocd"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.prometheus-stack.repoUrl }}
    targetRevision: {{ .Values.prometheus-stack.targetRevision }}
    helm:
      values: |
        prometheus:
        {{- toYaml .Values.prometheus-stack.values | nindent 10 }}  
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m