apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: "argocd"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.prometheusStack.repoURL }}
    targetRevision: {{ .Values.prometheusStack.targetRevision }}
  destination:   
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    path: cd/infra-charts/prometheus/
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m