apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  annotations:
{{ toYaml .Values.app.annotations | indent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  strategy:
{{ toYaml .Values.app.strategy | indent 4 }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      release: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.app.name }}:{{ .Values.image.version }}
          ports:
          {{- range .Values.app.ports }}
            - containerPort: {{ .value }}
              name: {{ .name }}
          {{- end }}
          {{- if .Values.app.envs }}
          env:
          {{- range .Values.app.envs }}
            - name: {{ .name }}
              value: {{ .value }}
          {{- end }}
          {{- end }}
