apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.name }}
    release: {{ .Release.Name }}
  ports:
  {{- range .Values.app.ports }}
  - port: {{ .value }}
    name: {{ .name }}
  {{- end }}