name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build and Pushing the Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    defaults:
      run:
        working-directory: './service/main'


    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build, tag, and push image to GHCR
      id: build-image
      run: |
        # Build a docker container and push it to GHCR
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        docker build -t ghcr.io/atilsensalduz/main:$git_hash .
        echo "Pushing image to GHCR..."
        docker push ghcr.io/atilsensalduz/main:$git_hash
        echo "::set-output name=image::ghcr.io/atilsensalduz/main:$git_hash"

    - name: manual approve before deploy
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: atilsensalduz

    - name: Update Version
      run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          version=$(cat ../../cd/charts/main/values.yaml | grep version: | awk '{print $2}')
          sed -i "s/$version/$git_hash/"  ../../cd/charts/main/values.yaml
          
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Version updated
